import { ApolloClient, InMemoryCache, gql } from '@apollo/client'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Characters API GraphQL Apollo Client</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </div>
  )
}

// export graphQL Apollo Client
export async function getStaticProps() {
  const client = new ApolloClient({
    uri: "https://rickandmortyapi.com/graphql/",
    cache: new InMemoryCache(),
  })
  const { data } = await client.query({
    query: gql`
    query {
      characters(page: 1) {
        info {
          count
          pages
        }
        results {
          name
          id
          location {
            name
            id
          }
          image
          origin {
            name
            id
          }
          episode {
            id
            episode
            air_date
          }
        }
      }
    }
    `,
  })

  return {
    props: {
      characters: data.characters.results,
    }
  }
}